pipeline {
    agent {
        label 'agent-windows'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/faty-mbengue/gestion-commande-backend.git',
                        credentialsId: 'tokenguitup'
                    ]]
                ])
            }
        }

        stage('Compile') {
            steps {
                dir('.') {  // S'assurer d'être à la racine
                    bat '.\\mvnw.cmd clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('.') {
                    bat '.\\mvnw.cmd test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('.') {
                    bat '.\\mvnw.cmd clean package -DskipTests'
                }
            }
        }
    }
}
