pipeline {
    agent {
        label 'agent-windows'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/faty-mbengue/gestion-commande-backend.git',
                        credentialsId: 'tokenguitup'
                    ]]
                ])
            }
        }

        stage('Compile') {
            steps {
                bat 'mvnw.cmd clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvnw.cmd test'
            }
        }

        stage('Package') {
            steps {
                bat 'mvnw.cmd clean package -DskipTests'
            }
        }
        
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
    
    post {
        success {
            echo '✅ Build Spring Boot réussi!'
        }
        failure {
            echo '❌ Build échoué'
        }
    }
}
